/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Tour } from "./index";

// @ts-ignore
export function indexTemplateHtml(this: Tour) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return (_vm.step)?_c('div',{staticClass:"tour-tip",style:(_vm.position)},[_c('span',{class:_vm.arrowClassName}),_c('div',{staticClass:"tour-content-wrapper"},[_c('p',[_vm._v(_vm._s(_vm.step.content))]),_c('a',{staticClass:"small button tour-next-tip",on:{"click":function($event){_vm.next()}}},[_vm._v(_vm._s(_vm.step.next))]),_c('a',{staticClass:"tour-close-tip",on:{"click":function($event){_vm.close()}}},[_vm._v("×")])])]):_vm._e()}
// tslint:enable
