// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
/* eslint-disable */
import { Tour } from "./index"

export function indexTemplateHtml(this: Tour) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return (_vm.step)?_c('div',{staticClass:"tour-tip",style:(_vm.position)},[_c('span',{class:_vm.arrowClassName}),_vm._v(" "),_c('div',{staticClass:"tour-content-wrapper"},[_c('p',[_vm._v(_vm._s(_vm.step.content))]),_vm._v(" "),_c('a',{staticClass:"small button tour-next-tip",on:{"click":function($event){return _vm.next()}}},[_vm._v(_vm._s(_vm.step.next))]),_vm._v(" "),_c('a',{staticClass:"tour-close-tip",on:{"click":function($event){return _vm.close()}}},[_vm._v("×")])])]):_vm._e()}
export var indexTemplateHtmlStatic = [  ]
/* eslint-enable */
// tslint:enable
